name: trabalho_g1
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  retrofit: ^4.0.1
  dio: ^5.1.1
  built_value: ^8.4.4
  json_annotation: ^4.8.0
  google_maps_flutter: ^2.2.5
  google_maps_flutter_web: ^0.4.0+8
  http: ^0.13.5
  json_serializable: ^6.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: ^6.0.0+3
  build_runner: ^2.3.3
  built_value_generator: ^8.4.4

flutter:

  uses-material-design: true

  assets:
    - assets/locations.json